### ISSUE TITLE
Using meld with git diff

### ISSUE THREAD

**Issue by james-prior** [mayaculpa/hapi#103]
I just discovered a way of using meld with git diff that obviates my gmd stuff.
The new way is:

    git difftool -t meld -y ...

where ... are the things to compare same as with the git diff command.
For example:

    git difftool -t meld -y 3196cfd 630bd3f

**Comment by PedroSFreitas** [comment]
Good to know!!! meld is definitely a nice piece of software. 👍

**Comment by james-prior** [comment]
I have come up with a couple of aliases in ~/.gitconfig to help.

    [alias]
        dm = difftool -t meld
        dy = difftool -t meld -y
