### ISSUE TITLE
Where is field defined?

### ISSUE THREAD

**Issue by james-prior** [mayaculpa/hapi#12]
Where is the value of field defined for SmartModule.send_alert_condition() in [smart_module/smart_module.py of 13cdfbc commit (of master branch)](https://github.com/mayaculpa/hapi/blob/13cdfbca795ce7c4527d3f2008b2824e3e6c2d99/src/smart_module/smart_module.py)?

**Comment by TylerReedMC** [comment]
That's just some old code that I'll be updating today.

**Comment by TylerReedMC** [comment]
James, if you like, drop me your email address and I'll get you an invite to the team chat server.
