### ISSUE TITLE
Set up Grafana on a public accessable server

### ISSUE THREAD

**Issue by moritz89** [mayaculpa/hapi#132]
- [x] Spin up a DigitalOcean server
- [x] Then, use Docker to
- [x] set up a public facing Grafana
- [x] with an InfluxDB database

**Comment by PedroSFreitas** [comment]
@moritz89 I'm not sure, but back when we were working on it @TylerReedMC had a small VPS for testing.
We already had Grafana and Influx configured. I'm not sure if that VPS still exists but could be interesting and save some time.

**Comment by moritz89** [comment]
He mentioned that he wanted to grant me access. Would be great as a reference to set up a docker instance.
@TylerReedMC Do you need my public key? and is it Windows or Linux?

**Comment by moritz89** [comment]
Created an Ubunut server with influxdb and grafana. Setup is handled by docker-compose to automate setup and data handling. Has the benefit of easy porting to docker-swarm at a later time. Project is located at https://github.com/moritz89/docker-influxdb-grafana and is accessible here: http://46.101.178.43:3000/

**Comment by PedroSFreitas** [comment]
That's great.
