### ISSUE TITLE
Is the man folder still needed?

### ISSUE THREAD

**Issue by moritz89** [mayaculpa/hapi#135]
Wanted to ask what the purpose of the man folder is, since the documentation currently lies in docs and has the proper format, RST and sphynx, as stated in #107

**Comment by PedroSFreitas** [comment]
The `man` would be used to hold the `docs` converted to `man` pages for Unix* systems. Example: `man smartmodule`.

Not sure if still relevant today.

**Comment by moritz89** [comment]
That seems a bit of an overkill to me

**Comment by PedroSFreitas** [comment]
It's your call. :)
