### ISSUE TITLE
How to handle short id?

### ISSUE THREAD

**Issue by james-prior** [mayaculpa/hapi#32]
What do you want to happen when len(id) < 16
in RTCInterface.set_id() of src/smart_module/rtc_interface.py?

ch = "" will likely cause ord(ch) to crash:

    jp@hapi:~$ python2
    Python 2.7.12+ (default, Sep  1 2016, 20:27:38) 
    [GCC 6.2.0 20160822] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> ch = ""
    >>> ord(ch)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: ord() expected a character, but string of length 0 found
    >>> 
    jp@hapi:~$ 

Additionally, is there an off-by-one bug in the len(id) < x text?

Ponder:

    jp@hapi:~$ python2
    Python 2.7.12+ (default, Sep  1 2016, 20:27:38) 
    [GCC 6.2.0 20160822] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> 'hello'.ljust(16)
    'hello           '
    >>> 
    jp@hapi:~$

**Comment by TylerReedMC** [comment]
Yes, good catches. Thanks. I've changed the "" to " " and will strip spaces when the values are read. Adjusted the len comparison to avoid off-by-one. Will push this evening when this is integrated wwith smart_module.py.

**Comment by TylerReedMC** [comment]
Resolved
