### ISSUE TITLE
readme/Master Controller Installation and Configuration V1.2.odt

### ISSUE THREAD

**Issue by james-prior** [mayaculpa/hapi#58]
What is purpose of sudo python -c "import psutil" command?

What Python code uses the gevent, pyserial, and w1thermsensor packages?

**Comment by TylerReedMC** [comment]
status.py uses psutil to gather system health information.
But that is old documentation, as there is no longer the concept of Master Controller or RTU. There was a time prior to MQTT adoption when we were using Telnet for communications, hence gevent. Pyserial was supported for computer to arduino comm, which it no longer is.

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> But that is old documentation ...

Please update the documentation.

The changes I have made have been from just looking at the code without running it.
I have taken much of the "low hanging fruit".
Further refactoring needs testing as demonstrated by speculative commits
which did not work out. 
I can not yet do the testing myself because I do not know how to install everything required.

**Comment by TylerReedMC** [comment]
I wasn't aware. The system should be able to run in "mock" mode, requiring no special hardware or support libraries. What issues do you run into when you try to run?

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> I wasn't aware. The system should be able to run in "mock" mode,
> requiring no special hardware or support libraries.

I had no idea that running in mock mode requires no special hardware
or support libraries. Please document that.
Also document the commands to run in mock mode.
When you say that no special hardware is required to run in "mock" mode,
does that mean mock mode can be run on PCs running MS Windows?

> What issues do you run into when you try to run?

Lack of documentation.

I do not get far enough to consider trying to run anything.
There are a thousand details in your head that are not written down.
You told me that the documentation I was using to try to install from 
was old, that even the concepts had changed. Trying to figure things
out from looking at source code, old documentation, and comments 
for pull requests and issues is slow and frustrating. 
There are many details that are obvious to you that I do not even know exist.
Without good documentation, the barrier will be high
for new contributors and new users, and the community will remain small.

For this project to prosper, it must have good documentation.

**Comment by TylerReedMC** [comment]
James,

I can't think of any reason the system wouldn't run on Windows, although I've never tried. I run in mock mode on Linux Mint and I run in "real" mode on a Raspberry Pi Zero W. There are also implementations for Arduino, ESP8266 and ESP32, in various degrees of maturity.

I understand your frustration. We're building and changing the technology at a very fast rate and documentation is lagging horribly. As the code base gels for Release 1, we'll start to emphasize documentation in the schedule. This should correspond with some new team members coming on-board as they finish their college finals, and it will be a good way for them to get a grip of the overall technical aspects of the system.

This project is an intersection of computers. embedded systems, data transformation and visualization and a host of physical products and appliances. Release 1 (slated for June) will be the merge point for multiple code bases, cloud services and physical product design and fabrication. And to your point, it all needs to be well documented.

However, the details are not entirely within my head. There are multiple conversations active all the time on the team communications server. We have about 10 people actively discussing various project aspects. Engineers, programmers, early adopters, entrepreneurs, etc. There are channels for Platform Engineering, Product Design, Cloud Services, etc. Discussions about "mock" capabilities, memory leaks, design sketches, etc. Shared files, flagged conversations, you name it. When new members come onto the project, I invite them to the communications server and often give them screen-shared overviews of the comm and scheduling tools.

So yes, until we get our documentation act together, it's more difficult for people to just find the project and start contributing. But until then (again, Release 1 is the target for that) we're getting by with tight team communications. If you'd like to join in those conversations, I'd be happy to send you another invite.

-Tyler
