### ISSUE TITLE
Possible bugs in /SDL_DS3231.py

### ISSUE THREAD

**Issue by james-prior** [mayaculpa/hapi#67]
There might be bugs in [SDL_DS3231.py](https://github.com/switchdoclabs/RTC_SDL_DS3231/blob/master/SDL_DS3231.py).

SDL_DS3231.read_datetime() calls other methods to read the date and time one byte at a time.
Imagine the situation where it is just before something rolls over,
such as just before midnight.
For example, 2017-05-22 23:59:59.
One reads the hours and minutes before midnight,
the the clock rolls over to the next day and one reads the  hours, year, month, and date.
For example, one reads 2017-05-23 00:59:59.
Then one calls .read_all() again and gets 2017-05-23 00:00:00,
giving the illusion that time went backwards.
One can get different crazy stuff if the most significant things
are read before the least significant things.

However, if one does a multibyte read from the chip, starting at address 0,
and reads all the time/date stuff in one multibyte read,
then one would get either 2017-05-22 23:59:59 or 2017-05-23 00:00:00,
not some unholy mix. Unfortunately SDL_DS3231.py does not do that.
Furthermore, the library it is based on, smbus, seems to come from
https://pypi.python.org/pypi.smbus-cffi/0.5.1, which states in part:

    Note of caution for Raspberry Pi users: when calling read_block_data ...
    the underlying i2/smbus library/driver causes a kernel panic on the
    Raspberry Pi.

Work arounds include:

- continuing to use SDL_DS3231.py:
    - call SDL_DS3231.read_datetime() until two successive return values are the same.
- use some other code for DS3231. There are probably alternatives.

By the way, does python guarantee order of evaluation of arguments?

**Comment by TylerReedMC** [comment]
Order is guaranteed, left to right. 
Let's go with "call SDL_DS3231.read_datetime() until two successive return values are the same", at least until a better library raises it's beautiful head.

**Comment by TylerReedMC** [comment]
https://docs.python.org/2/reference/expressions.html#evaluation-order

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> https://docs.python.org/2/reference/expressions.html#evaluation-order

One of those examples addressed the point:

    expr1(expr2, expr3, *expr4, **expr5)

Thanks!

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> Let's go with "call SDL_DS3231.read_datetime()
> until two successive return values are the same",
> at least until a better library raises it's beautiful head.

OK

**Comment by james-prior** [comment]
I have opened an
[issue](https://github.com/switchdoclabs/RTC_SDL_DS3231/issues/2)
and sent a
[pull request](https://github.com/switchdoclabs/RTC_SDL_DS3231/pull/3)
to https://github.com/switchdoclabs/RTC_SDL_DS3231,
but have yet to hear any response to a 
[different pull request from weeks ago](https://github.com/switchdoclabs/RTC_SDL_DS3231/pull/1).

**Comment by james-prior** [comment]
Earlier I wrote about the https://github.com/switchdoclabs/RTC_SDL_DS3231 project,

> ...but have yet to hear any response to a
> different pull request from weeks ago.

Well, my pull requests were just merged.
They still need to be tested.

**Comment by PedroSFreitas** [comment]
@james-prior and @TylerReedMC closing this Issue since it was already addressed upstream.
If anything, we re-open it.
