### ISSUE TITLE
undefined acronym: FMS

### ISSUE THREAD

**Issue by herrold** [mayaculpa/hapi#81]
I see a commit:
    readme/FMS.Requirements.rst

what is a FMS ?

**Comment by TylerReedMC** [comment]
FMS = Facility Management System   The temporary name of the Android app being built to give users access to and control over their automation assets.

**Comment by TylerReedMC** [comment]
Here's the public view of the [schedule for FMS](http://primeradiant.technology/kanboard/?controller=BoardViewController&action=readonly&token=e7078d9bbe076afa4317a42ff943fe38597ad18a8f92eea904b067829606)

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> Here's the public view ...

Wow, no registration required to read! Thanks!

**Comment by TylerReedMC** [comment]
[Platform Engineering](http://primeradiant.technology/kanboard/?controller=BoardViewController&action=readonly&token=af29db0d68f4df03b3fec029833a6dd3f2cebc9d951d77da18ea359a4b4f)
[Product Design](http://primeradiant.technology/kanboard/?controller=BoardViewController&action=readonly&token=86d31e405d846bda86d7da5a59c0446bb1ce7f8245cd7eb70997d558c863)
